#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_kb_js.py — Generate data.kb.js from kb.py (46 prerequisite modules).
Run:  python gen_kb_js.py
Output: assets/scripts/data.kb.js
"""
import json, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "generator"))
import kb

out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", "scripts")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "data.kb.js")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by gen_kb_js.py — 46 prerequisite knowledge modules (2000+ chars each)\n")
    f.write("window.KB_DATA = ")
    json.dump(kb.KB, f, ensure_ascii=False, indent=1)
    f.write(";\n")
    f.write("window.KB_UNIVERSAL = ")
    json.dump(kb.UNIVERSAL_PREREQS, f, ensure_ascii=False)
    f.write(";\n")
    f.write("window.KB_DISCIPLINE = ")
    json.dump(kb.DISCIPLINE_PREREQS, f, ensure_ascii=False, indent=1)
    f.write(";\n")
    f.write("window.KB_SPECIFIC = ")
    json.dump(kb.SUBFIELD_SPECIFIC, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print("Generated %s with %d modules" % (out_path, len(kb.KB)))
